-- Core tables are in Prisma schema. This file includes enums and notes for Postgres.

-- Enums are generated by Prisma; ensure they map to the expected values.
-- Consider partial indexes for submissions by status to optimize admin queues.

CREATE INDEX IF NOT EXISTS idx_submissions_status ON submissions (status);
CREATE INDEX IF NOT EXISTS idx_points_ledger_created ON points_ledger (created_at);

-- RBAC note: use Postgres RLS if deploying on Supabase. Example policies (pseudocode):
--  - participants can insert submissions with user_id = auth.uid()
--  - participants can select own submissions; public profiles read approved+public
--  - reviewers/admins can update status and insert ledger entries
